
language: perl

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - cpanminus
      - r-base-dev  
cache:
  directories:
    - ~/travis_R_lib

services:
  - docker
      
before_install:
  - echo 'R_LIBS=~/travis_R_lib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e '{ install.packages("ape", dependencies = TRUE, lib = "~/travis_R_lib")}'
  - cpanm -nf Statistics::R || cat /home/travis/.cpanm/work/*/build.log
  - cpanm -n JSON
  - ./build_3rd_party.sh ~

script:
  - docker build -t shchurch/sowhat:$TRAVIS_BRANCH . 

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push shchurch/sowhat:$TRAVIS_BRANCH
  on:
     all_branches: true
     condition: $TRAVIS_BRANCH =~ ^master|Development$
